/**
 * Smart Folders Types
 * Part of v1.4.0 AI-Powered Intelligence
 */

// ============================================================================
// Enums
// ============================================================================

export enum FolderType {
  /** Automatically created by AI */
  AUTO = 'AUTO',
  /** User created manually */
  MANUAL = 'MANUAL',
  /** System default folder */
  SYSTEM = 'SYSTEM',
  /** Temporary folder for grouping */
  TEMPORARY = 'TEMPORARY',
}

export enum OrganizationStrategy {
  /** Organize by sender */
  BY_SENDER = 'BY_SENDER',
  /** Organize by topic/subject */
  BY_TOPIC = 'BY_TOPIC',
  /** Organize by priority/importance */
  BY_PRIORITY = 'BY_PRIORITY',
  /** Organize by project/keyword */
  BY_PROJECT = 'BY_PROJECT',
  /** Organize by time period */
  BY_TIME = 'BY_TIME',
  /** Custom clustering */
  CLUSTERING = 'CLUSTERING',
  /** Mixed approach */
  HYBRID = 'HYBRID',
}

export enum FolderCategory {
  /** Work-related emails */
  WORK = 'WORK',
  /** Personal emails */
  PERSONAL = 'PERSONAL',
  /** Promotional emails */
  PROMOTIONS = 'PROMOTIONS',
  /** Social media notifications */
  SOCIAL = 'SOCIAL',
  /** Financial emails */
  FINANCE = 'FINANCE',
  /** Travel-related emails */
  TRAVEL = 'TRAVEL',
  /** Shopping/receipts */
  SHOPPING = 'SHOPPING',
  /** Newsletters */
  NEWSLETTERS = 'NEWSLETTERS',
  /** Automated/system emails */
  SYSTEM = 'SYSTEM',
  /** Uncategorized */
  OTHER = 'OTHER',
}

export enum ConfidenceLevel {
  /** Very confident in folder assignment */
  HIGH = 'HIGH',
  /** Moderately confident */
  MEDIUM = 'MEDIUM',
  /** Low confidence, needs review */
  LOW = 'LOW',
}

export enum EmailPriority {
  /** Urgent, immediate attention needed */
  URGENT = 'URGENT',
  /** High priority */
  HIGH = 'HIGH',
  /** Normal priority */
  NORMAL = 'NORMAL',
  /** Low priority */
  LOW = 'LOW',
}

// ============================================================================
// Interfaces
// ============================================================================

export interface EmailForOrganization {
  id: string;
  subject: string;
  body: string;
  from: string;
  to: string[];
  cc?: string[];
  date: string;
  hasAttachments: boolean;
  tags?: string[];
  readStatus: 'read' | 'unread';
}

export interface SmartFolder {
  id: string;
  name: string;
  type: FolderType;
  category: FolderCategory;
  description?: string;
  emailCount: number;
  unreadCount: number;
  strategy: OrganizationStrategy;
  rules: FolderRule[];
  color?: string;
  icon?: string;
  createdAt: string;
  updatedAt: string;
  lastActivity: string;
  metadata: FolderMetadata;
}

export interface FolderRule {
  id: string;
  type: 'SENDER' | 'SUBJECT' | 'KEYWORD' | 'PRIORITY' | 'TIME' | 'ATTACHMENT';
  condition: string;
  value: string;
  weight: number;
}

export interface FolderMetadata {
  confidence: ConfidenceLevel;
  averagePriority: EmailPriority;
  topSenders: string[];
  topKeywords: string[];
  commonTopics: string[];
  autoGenerated: boolean;
  lastOptimization: string;
}

export interface Suggestion {
  id: string;
  folderName: string;
  category: FolderCategory;
  strategy: OrganizationStrategy;
  emailCount: number;
  confidence: number;
  keywords: string[];
  sampleEmails: string[];
  reason: string;
  timestamp: string;
}

export interface RoutingResult {
  emailId: string;
  folderId: string;
  confidence: number;
  alternativeFolders: Array<{ folderId: string; confidence: number }>;
  reason: string;
  timestamp: string;
}

export interface OrganizationConfig {
  /** Strategy to use for organization */
  strategy: OrganizationStrategy;
  /** Minimum confidence for automatic routing */
  minConfidence: number;
  /** Maximum number of folders to suggest */
  maxSuggestions: number;
  /** Enable automatic folder creation */
  autoCreateFolders: boolean;
  /** Enable learning from user actions */
  enableLearning: boolean;
  /** Enable cache for performance */
  enableCache: boolean;
  /** Minimum email count to create folder */
  minEmailsForFolder: number;
  /** Weight for subject analysis */
  subjectWeight: number;
  /** Weight for body analysis */
  bodyWeight: number;
  /** Weight for sender analysis */
  senderWeight: number;
}

export interface OrganizationStatistics {
  totalEmailsProcessed: number;
  totalFoldersCreated: number;
  totalFoldersSuggested: number;
  totalRoutings: number;
  averageConfidence: number;
  emailsByCategory: Record<FolderCategory, number>;
  foldersByType: Record<FolderType, number>;
  accuracy: number;
  totalProcessingTime: number;
  averageProcessingTime: number;
  cacheHits: number;
  cacheMisses: number;
}

export interface UserAction {
  emailId: string;
  folderId: string;
  action: 'MOVED' | 'ACCEPTED' | 'REJECTED' | 'MANUAL';
  timestamp: string;
}

export interface OrganizationContext {
  emails: EmailForOrganization[];
  existingFolders?: SmartFolder[];
  userHistory?: UserAction[];
  config?: Partial<OrganizationConfig>;
}

// ============================================================================
// Default Configuration
// ============================================================================

export const DEFAULT_ORGANIZATION_CONFIG: OrganizationConfig = {
  strategy: OrganizationStrategy.HYBRID,
  minConfidence: 0.6,
  maxSuggestions: 5,
  autoCreateFolders: false,
  enableLearning: true,
  enableCache: true,
  minEmailsForFolder: 3,
  subjectWeight: 0.3,
  bodyWeight: 0.5,
  senderWeight: 0.2
};

// ============================================================================
// Constants
// ============================================================================

/** Common work-related keywords */
export const WORK_KEYWORDS = [
  'project', 'meeting', 'report', 'deadline', 'presentation',
  'proposal', 'invoice', 'contract', 'review', 'approval',
  'schedule', 'calendar', 'task', 'assign', 'deliverable',
  'milestone', 'quarterly', 'annual', 'budget', 'team'
];

/** Personal email keywords */
export const PERSONAL_KEYWORDS = [
  'family', 'friend', 'personal', 'birthday', 'wedding',
  'vacation', 'party', 'invitation', 'dinner', 'weekend',
  'holiday', 'trip', 'photos', 'congratulations', 'thanks'
];

/** Promotional keywords */
export const PROMOTIONS_KEYWORDS = [
  'sale', 'discount', 'offer', 'deal', 'promo', 'coupon',
  'limited time', 'special', 'exclusive', 'save', 'free',
  'off', 'buy now', 'order', 'shop', 'store'
];

/** Financial keywords */
export const FINANCE_KEYWORDS = [
  'bank', 'account', 'statement', 'payment', 'transaction',
  'deposit', 'withdrawal', 'transfer', 'credit', 'debit',
  'invoice', 'receipt', 'tax', 'refund', 'investment'
];

/** Travel-related keywords */
export const TRAVEL_KEYWORDS = [
  'flight', 'hotel', 'booking', 'reservation', 'itinerary',
  'airport', 'airline', 'car rental', 'vacation', 'trip',
  'passport', 'visa', 'check-in', 'luggage', 'boarding'
];

/** Shopping keywords */
export const SHOPPING_KEYWORDS = [
  'order', 'shipped', 'delivery', 'purchase', 'confirm',
  'receipt', 'invoice', 'thank you', 'your order', 'item',
  'package', 'tracking', 'store', 'checkout'
];

/** Newsletter keywords */
export const NEWSLETTER_KEYWORDS = [
  'newsletter', 'digest', 'weekly', 'monthly', 'update',
  'unsubscribe', 'bulletin', 'news', 'edition', 'issue',
  'subscribe', 'alert', 'notification'
];

/** Priority indicators */
export const URGENT_KEYWORDS = [
  'urgent', 'asap', 'immediate', 'emergency', 'critical',
  'deadline', 'important', 'priority', 'attention'
];

/** System email indicators */
export const SYSTEM_SENDERS = [
  'noreply', 'no-reply', 'donotreply', 'support', 'notifications',
  'alert', 'system', 'admin', 'bot', 'auto'
];

/** Confidence thresholds */
export const CONFIDENCE_THRESHOLDS = {
  HIGH: 0.8,
  MEDIUM: 0.6,
  LOW: 0.4
} as const;

/** Topic extraction patterns */
export const TOPIC_PATTERNS = [
  /project\s+(\w+)/i,
  /meeting\s+(?:about|regarding)?\s*(\w+)/i,
  /(\w+)\s+update/i,
  /(\w+)\s+review/i,
  /(\w+)\s+report/i
];
